// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for linux - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxg-0DpBPa4SPlx0aIZnjRZH3dwzYJktc',
    appId: '1:671290491142:web:d50972ba0a0c1aaf4e5e87',
    messagingSenderId: '671290491142',
    projectId: 'single-store-ecommerce',
    authDomain: 'single-store-ecommerce.firebaseapp.com',
    storageBucket: 'single-store-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ5zwSq9e07WRU8qxHi1Wonz1xwLFoGhU',
    appId: '1:671290491142:android:0ad9bd86a57d11074e5e87',
    messagingSenderId: '671290491142',
    projectId: 'single-store-ecommerce',
    storageBucket: 'single-store-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSDJbu_ojdXIN3S87Fc8HKGWDykYL1_J0',
    appId: '1:671290491142:ios:a78280bddade96c54e5e87',
    messagingSenderId: '671290491142',
    projectId: 'single-store-ecommerce',
    storageBucket: 'single-store-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.singleStoreEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSDJbu_ojdXIN3S87Fc8HKGWDykYL1_J0',
    appId: '1:671290491142:ios:a78280bddade96c54e5e87',
    messagingSenderId: '671290491142',
    projectId: 'single-store-ecommerce',
    storageBucket: 'single-store-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.singleStoreEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxg-0DpBPa4SPlx0aIZnjRZH3dwzYJktc',
    appId: '1:671290491142:web:d29562ba495df3ba4e5e87',
    messagingSenderId: '671290491142',
    projectId: 'single-store-ecommerce',
    authDomain: 'single-store-ecommerce.firebaseapp.com',
    storageBucket: 'single-store-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDxg-0DpBPa4SPlx0aIZnjRZH3dwzYJktc',
    appId: '1:671290491142:web:8986dd6786d59fe74e5e87',
    messagingSenderId: '671290491142',
    projectId: 'single-store-ecommerce',
    authDomain: 'single-store-ecommerce.firebaseapp.com',
    storageBucket: 'single-store-ecommerce.firebasestorage.app',
  );

}